// Code generated by hertz generator.

package favoriteapi

import (
	"context"
	"douyin/biz/rpc"
	"douyin/kitex_gen/favorite"
	"log"

	favoriteapi "douyin/biz/model/favoriteapi"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FavoriteAction .
// @router /douyin/favorite/favorite_action/ [POST]
func FavoriteAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favoriteapi.DouyinFavoriteActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	res, err := rpc.FavoriteAction(context.Background(), &favorite.DouyinFavoriteActionRequest{
		Token:      req.Token,
		VideoId:    req.VideoId,
		ActionType: req.ActionType,
	})
	if err != nil {
		log.Printf(err.Error())
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := &favorite.DouyinFavoriteActionResponse{
		StatusCode: res.StatusCode,
		StatusMsg:  res.StatusMsg,
	}

	c.JSON(consts.StatusOK, resp)
}

// FavoriteList .
// @router /douyin/favorite/favorite_list/ [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favoriteapi.DouyinFavoriteListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	res, err := rpc.FavoriteList(context.Background(), &favorite.DouyinFavoriteListRequest{
		UserId: req.UserId,
		Token:  req.Token,
	})
	if err != nil {
		log.Printf(err.Error())
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := &favorite.DouyinFavoriteListResponse{
		StatusCode: res.StatusCode,
		StatusMsg:  res.StatusMsg,
		VideoList:  res.VideoList,
	}
	c.JSON(consts.StatusOK, resp)
}
