// Code generated by hertz generator.

package favoriteapi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favorite_actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favorite_listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoritelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
